# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/universal7420-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter zerofltecan zeroltecan zerofltexx zeroltexx,$(TARGET_DEVICE)),)

endif
