# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/universal7420-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter zerofltecan zeroltecan zerofltexx zeroltexx noblelte nobleltecan nobleltedd nobleltedv nobleltejv nobleltektt nobleltelgt noblelteskt nobleltespr nobleltetmo nobleltextc nobleltezt zenlte zenltecan zenltedd zenltedv zenltejv zenltektt zenltelgt zenlteskt zenltetmo zenltexx zenltezt,$(TARGET_DEVICE)),)

endif
