# Copyright (C) 2015-2016 The CyanogenMod Project
# Copyright (C) 2017-2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/zerofltexx/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/zerofltexx

PRODUCT_COPY_FILES += \
    vendor/samsung/zerofltexx/proprietary/bin/gps.cer:$(TARGET_COPY_OUT_SYSTEM)/bin/gps.cer \
    vendor/samsung/zerofltexx/proprietary/bin/gpsd:$(TARGET_COPY_OUT_SYSTEM)/bin/gpsd \
    vendor/samsung/zerofltexx/proprietary/bin/lhd:$(TARGET_COPY_OUT_SYSTEM)/bin/lhd \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/clearwater-dsp3-tx-nb.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/clearwater-dsp3-tx-nb.bin \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/clearwater-dsp3-tx-swb-interview.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/clearwater-dsp3-tx-swb-interview.bin \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/clearwater-dsp3-tx-wb.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/clearwater-dsp3-tx-wb.bin \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/clearwater-dsp4-rx-anc-nb.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/clearwater-dsp4-rx-anc-nb.bin \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/clearwater-dsp4-rx-anc-wb.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/clearwater-dsp4-rx-anc-wb.bin \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/clearwater-dsp6-lpsd-control.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/clearwater-dsp6-lpsd-control.bin \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/clearwatera-dsp2-tx-nb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/clearwatera-dsp2-tx-nb.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/clearwatera-dsp2-tx-swb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/clearwatera-dsp2-tx-swb.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/clearwatera-dsp2-tx-wb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/clearwatera-dsp2-tx-wb.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/clearwatera-dsp3-tx-nb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/clearwatera-dsp3-tx-nb.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/clearwatera-dsp3-tx-swb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/clearwatera-dsp3-tx-swb.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/clearwatera-dsp3-tx-wb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/clearwatera-dsp3-tx-wb.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/clearwatera-dsp4-rx-anc-nb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/clearwatera-dsp4-rx-anc-nb.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/clearwatera-dsp4-rx-anc-wb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/clearwatera-dsp4-rx-anc-wb.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/clearwatera-dsp5-dsm.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/clearwatera-dsp5-dsm.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/clearwatera-dsp6-ez2-control.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/clearwatera-dsp6-ez2-control.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/clearwaterc-dsp1-trace.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/clearwaterc-dsp1-trace.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/clearwaterc-dsp2-tx-nb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/clearwaterc-dsp2-tx-nb.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/clearwaterc-dsp2-tx-swb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/clearwaterc-dsp2-tx-swb.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/clearwaterc-dsp2-tx-wb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/clearwaterc-dsp2-tx-wb.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/clearwaterc-dsp3-tx-nb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/clearwaterc-dsp3-tx-nb.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/clearwaterc-dsp3-tx-swb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/clearwaterc-dsp3-tx-swb.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/clearwaterc-dsp3-tx-wb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/clearwaterc-dsp3-tx-wb.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/clearwaterc-dsp4-rx-anc-nb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/clearwaterc-dsp4-rx-anc-nb.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/clearwaterc-dsp4-rx-anc-wb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/clearwaterc-dsp4-rx-anc-wb.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/clearwaterc-dsp5-dsm.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/clearwaterc-dsp5-dsm.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/clearwaterc-dsp6-ez2-control.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/clearwaterc-dsp6-ez2-control.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/florida-dsp1-edac.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp1-edac.bin \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/florida-dsp1-edac.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp1-edac.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/florida-dsp2-tx-fb-meeting.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp2-tx-fb-meeting.bin \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/florida-dsp2-tx-fb-meeting.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp2-tx-fb-meeting.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/florida-dsp2-tx-nb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp2-tx-nb.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/florida-dsp2-tx-swb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp2-tx-swb.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/florida-dsp2-tx-wb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp2-tx-wb.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/florida-dsp3-ez2-control.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp3-ez2-control.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/florida-dsp3-lpsd-control.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp3-lpsd-control.bin \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/florida-dsp3-tx-nb.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp3-tx-nb.bin \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/florida-dsp3-tx-nb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp3-tx-nb.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/florida-dsp3-tx-swb-conversation.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp3-tx-swb-conversation.bin \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/florida-dsp3-tx-swb-interview.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp3-tx-swb-interview.bin \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/florida-dsp3-tx-swb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp3-tx-swb.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/florida-dsp3-tx-wb-meeting.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp3-tx-wb-meeting.bin \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/florida-dsp3-tx-wb-meeting.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp3-tx-wb-meeting.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/florida-dsp3-tx-wb.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp3-tx-wb.bin \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/florida-dsp3-tx-wb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp3-tx-wb.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/florida-dsp4-dsm.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp4-dsm.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/florida-dsp4-rx-anc-nb.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp4-rx-anc-nb.bin \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/florida-dsp4-rx-anc-nb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp4-rx-anc-nb.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/florida-dsp4-rx-anc-wb.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp4-rx-anc-wb.bin \
    vendor/samsung/zerofltexx/proprietary/etc/firmware/florida-dsp4-rx-anc-wb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp4-rx-anc-wb.wmfw \
    vendor/samsung/zerofltexx/proprietary/etc/nfc/sec_s3fwrn5p_rfreg.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/nfc/sec_s3fwrn5p_rfreg.bin \
    vendor/samsung/zerofltexx/proprietary/vendor/etc/wifi/bcmdhd_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/zerofltexx/proprietary/vendor/etc/wifi/bcmdhd_apsta.bin_a1:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_apsta.bin_a1 \
    vendor/samsung/zerofltexx/proprietary/vendor/etc/wifi/bcmdhd_ibss.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_ibss.bin \
    vendor/samsung/zerofltexx/proprietary/vendor/etc/wifi/bcmdhd_ibss.bin_a1:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_ibss.bin_a1 \
    vendor/samsung/zerofltexx/proprietary/vendor/etc/wifi/bcmdhd_mfg.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/zerofltexx/proprietary/vendor/etc/wifi/bcmdhd_mfg.bin_a1:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_mfg.bin_a1 \
    vendor/samsung/zerofltexx/proprietary/vendor/etc/wifi/bcmdhd_sta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/zerofltexx/proprietary/vendor/etc/wifi/bcmdhd_sta.bin_a1:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_sta.bin_a1 \
    vendor/samsung/zerofltexx/proprietary/vendor/etc/wifi/cred.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/cred.conf \
    vendor/samsung/zerofltexx/proprietary/vendor/etc/wifi/nvram_mfg.txt:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_mfg.txt \
    vendor/samsung/zerofltexx/proprietary/vendor/etc/wifi/nvram_mfg.txt_a1:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_mfg.txt_a1 \
    vendor/samsung/zerofltexx/proprietary/vendor/etc/wifi/nvram_mfg.txt_b85_a1:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_mfg.txt_b85_a1 \
    vendor/samsung/zerofltexx/proprietary/vendor/etc/wifi/nvram_mfg.txt_murata:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_mfg.txt_murata \
    vendor/samsung/zerofltexx/proprietary/vendor/etc/wifi/nvram_mfg.txt_murata_a1:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_mfg.txt_murata_a1 \
    vendor/samsung/zerofltexx/proprietary/vendor/etc/wifi/nvram_mfg.txt_murata_b85_a1:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_mfg.txt_murata_b85_a1 \
    vendor/samsung/zerofltexx/proprietary/vendor/etc/wifi/nvram_mfg.txt_wisol:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_mfg.txt_wisol \
    vendor/samsung/zerofltexx/proprietary/vendor/etc/wifi/nvram_mfg.txt_wisol_a1:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_mfg.txt_wisol_a1 \
    vendor/samsung/zerofltexx/proprietary/vendor/etc/wifi/nvram_mfg.txt_wisol_b85_a1:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_mfg.txt_wisol_b85_a1 \
    vendor/samsung/zerofltexx/proprietary/vendor/etc/wifi/nvram_net.txt:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_net.txt \
    vendor/samsung/zerofltexx/proprietary/vendor/etc/wifi/nvram_net.txt_a1:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_net.txt_a1 \
    vendor/samsung/zerofltexx/proprietary/vendor/etc/wifi/nvram_net.txt_b85_a1:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_net.txt_b85_a1 \
    vendor/samsung/zerofltexx/proprietary/vendor/etc/wifi/nvram_net.txt_murata:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_net.txt_murata \
    vendor/samsung/zerofltexx/proprietary/vendor/etc/wifi/nvram_net.txt_murata_a1:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_net.txt_murata_a1 \
    vendor/samsung/zerofltexx/proprietary/vendor/etc/wifi/nvram_net.txt_murata_b85_a1:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_net.txt_murata_b85_a1 \
    vendor/samsung/zerofltexx/proprietary/vendor/etc/wifi/nvram_net.txt_wisol:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_net.txt_wisol \
    vendor/samsung/zerofltexx/proprietary/vendor/etc/wifi/nvram_net.txt_wisol_a1:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_net.txt_wisol_a1 \
    vendor/samsung/zerofltexx/proprietary/vendor/etc/wifi/nvram_net.txt_wisol_b85_a1:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_net.txt_wisol_b85_a1 \
    vendor/samsung/zerofltexx/proprietary/vendor/etc/wifi/wpa_supplicant.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant.conf \
    vendor/samsung/zerofltexx/proprietary/lib/egl/egl.cfg:$(TARGET_COPY_OUT_SYSTEM)/lib/egl/egl.cfg \
    vendor/samsung/zerofltexx/proprietary/lib/egl/libGLES_android.so:$(TARGET_COPY_OUT_SYSTEM)/lib/egl/libGLES_android.so \
    vendor/samsung/zerofltexx/proprietary/lib/hw/camera.exynos5.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/camera.exynos5.so \
    vendor/samsung/zerofltexx/proprietary/lib/hw/consumerir.exynos5.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/consumerir.exynos5.so \
    vendor/samsung/zerofltexx/proprietary/lib/hw/sensors.universal7420.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/sensors.universal7420.so \
    vendor/samsung/zerofltexx/proprietary/lib/libexynoscamera.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libexynoscamera.so \
    vendor/samsung/zerofltexx/proprietary/lib/libexynoscamera3.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libexynoscamera3.so \
    vendor/samsung/zerofltexx/proprietary/lib/libfloatingfeature.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libfloatingfeature.so \
    vendor/samsung/zerofltexx/proprietary/lib/libhwjpeg.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libhwjpeg.so \
    vendor/samsung/zerofltexx/proprietary/lib/libprotobuf-cpp-fl24.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libprotobuf-cpp-fl24.so \
    vendor/samsung/zerofltexx/proprietary/vendor/lib/libsec-ril-dsds.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsec-ril-dsds.so \
    vendor/samsung/zerofltexx/proprietary/vendor/lib/libsec-ril.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsec-ril.so \
    vendor/samsung/zerofltexx/proprietary/lib/libsensorlistener.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsensorlistener.so \
    vendor/samsung/zerofltexx/proprietary/lib/libuniplugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libuniplugin.so \
    vendor/samsung/zerofltexx/proprietary/lib/libwrappergps.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libwrappergps.so \
    vendor/samsung/zerofltexx/proprietary/lib64/egl/libGLES_android.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/egl/libGLES_android.so \
    vendor/samsung/zerofltexx/proprietary/lib64/hw/camera.exynos5.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/hw/camera.exynos5.so \
    vendor/samsung/zerofltexx/proprietary/lib64/hw/consumerir.exynos5.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/hw/consumerir.exynos5.so \
    vendor/samsung/zerofltexx/proprietary/lib64/hw/gps.default.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/hw/gps.default.so \
    vendor/samsung/zerofltexx/proprietary/lib64/hw/sensors.universal7420.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/hw/sensors.universal7420.so \
    vendor/samsung/zerofltexx/proprietary/lib64/libexynoscamera.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libexynoscamera.so \
    vendor/samsung/zerofltexx/proprietary/lib64/libexynoscamera3.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libexynoscamera3.so \
    vendor/samsung/zerofltexx/proprietary/lib64/libfloatingfeature.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libfloatingfeature.so \
    vendor/samsung/zerofltexx/proprietary/lib64/libhwjpeg.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libhwjpeg.so \
    vendor/samsung/zerofltexx/proprietary/lib64/libprotobuf-cpp-fl24.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libprotobuf-cpp-fl24.so \
    vendor/samsung/zerofltexx/proprietary/vendor/lib64/libsec-ril-dsds.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsec-ril-dsds.so \
    vendor/samsung/zerofltexx/proprietary/vendor/lib64/libsec-ril.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsec-ril.so \
    vendor/samsung/zerofltexx/proprietary/lib64/libsensorlistener.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libsensorlistener.so \
    vendor/samsung/zerofltexx/proprietary/lib64/libuniplugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libuniplugin.so \
    vendor/samsung/zerofltexx/proprietary/lib64/libwrappergps.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libwrappergps.so \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/bcm4358A3_V0083.0138.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4358A3_V0083.0138.hcd \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/bcm4358A3_V0083.0138_murata.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4358A3_V0083.0138_murata.hcd \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/bcm4358A3_V0083.0138_semco.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4358A3_V0083.0138_semco.hcd \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/bcm4358A3_V0083.0138_semco3rd.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4358A3_V0083.0138_semco3rd.hcd \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/bcm4358A3_V0083.0138_wisol.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4358A3_V0083.0138_wisol.hcd \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/companion_2p2_master_setfile.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/companion_2p2_master_setfile.bin \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/companion_2p2_mode_setfile.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/companion_2p2_mode_setfile.bin \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/companion_fw_2p2_evt1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/companion_fw_2p2_evt1.bin \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/companion_fw_imx240_evt1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/companion_fw_imx240_evt1.bin \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/companion_imx240_master_setfile.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/companion_imx240_master_setfile.bin \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/companion_imx240_mode_setfile.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/companion_imx240_mode_setfile.bin \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/fimc_is_fw2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_fw2.bin \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/fimc_is_fw2_2p2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_fw2_2p2.bin \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/fimc_is_fw2_imx240.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_fw2_imx240.bin \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/mfc_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mfc_fw.bin \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/nfc/sec_s3fwrn5p_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nfc/sec_s3fwrn5p_firmware.bin \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/ois_fw_dom.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ois_fw_dom.bin \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/ois_fw_sec.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ois_fw_sec.bin \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/seiren_fw_dram.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/seiren_fw_dram.bin \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/seiren_fw_sram.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/seiren_fw_sram.bin \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/setfile_2p2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_2p2.bin \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/setfile_4e6.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_4e6.bin \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/setfile_6b2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_6b2.bin \
    vendor/samsung/zerofltexx/proprietary/vendor/firmware/setfile_imx240.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_imx240.bin \
    vendor/samsung/zerofltexx/proprietary/vendor/lib/egl/libGLES_mali.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLES_mali.so \
    vendor/samsung/zerofltexx/proprietary/vendor/lib64/egl/libGLES_mali.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libGLES_mali.so
